### ISSUE TITLE
Replace log4j 2.x by slf4j ?

### ISSUE THREAD

**Issue by sbouchex** [plan-vision/jett-poi4#1]
Any chance to replace log4j 2x by slf4j in order to let the user plug its own logger ?

**Comment by tran4o** [comment]
As much i'm aware poi and another dependencies use log4j to too. I think the right approach is to remove the log4j jars and add some log4j > slf4j adapter. I dont have plans to develop the library, it's just a replacement till the  author / some future developer moves the original project or a branch of it to a new stable version.
